test actions

diff --git a/.github/workflows/WRT-CORE.yml b/.github/workflows/WRT-CORE.yml
--- a/.github/workflows/WRT-CORE.yml
+++ b/.github/workflows/WRT-CORE.yml
@@ -170,9 +170,14 @@ jobs:
       - name: Update Feeds
         run: |
           cd ./wrt/
+          set -x
 
           ./scripts/feeds update -a
-          ./scripts/feeds install -a
+          ./scripts/feeds install -a  2>&1 | tee feeds_install.log || {
+             echo "❌ feeds install failed"
+             tail -n 200 feeds_install.log
+             exit 1
+          }
 
       - name: Custom Packages
         run: |
